base:
  project: pricing-project
  random_state: 32
  target_col: median_house_value

data_source:
  gdrive_source: data_given/housing.csv

load_data:
  raw_dataset_csv: data/raw/housing.csv

split_data:
  train_path: data/processed/train_housing.csv
  test_path: data/processed/test_housing.csv
  test_size: 0.2

estimators:
  ElasticNet:
    params:
      alpha: 0.9
      l1_ratio: 0.4

model_dir: saved_models

